[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "MPL-2.0",
    "OFL-1.1",
    "Unicode-DFS-2016",
    "Zlib",
]

[advisories]
# Used by iced-lazy v0.6.1
ignore = ["RUSTSEC-2023-0042"]

[bans]
multiple-versions = "deny"
skip = [
    { name = "arrayvec", version = "0.5"},
    { name = "async-channel", version = "1.9"},
    { name = "async-io", version = "1.13"},
    { name = "async-lock", version = "2.8"},
    { name = "bitflags", version = "1.3"},
    { name = "calloop", version = "0.10"},
    { name = "cocoa", version = "0.24"},
    { name = "core-graphics", version = "0.22"},
    { name = "foreign-types", version = "0.3"},
    { name = "event-listener", version = "2.5"},
    { name = "event-listener", version = "3.1"},
    { name = "fastrand", version = "1.9"},
    { name = "foreign-types-shared", version = "0.1"},
    { name = "futures-lite", version = "1.13"},
    { name = "hashbrown", version = "0.12"},
    { name = "indexmap", version = "1.9"},
    { name = "libloading", version = "0.7"},
    { name = "linux-raw-sys", version = "0.3"},
    { name = "memmap2", version = "0.5"},
    { name = "memoffset", version = "0.6"},
    { name = "nix", version = "0.24"},
    { name = "nix", version = "0.25"},
    { name = "parking_lot", version = "0.11"},
    { name = "parking_lot_core", version = "0.8"},
    { name = "polling", version = "2.8"},
    { name = "redox_syscall", version = "0.2"},
    { name = "raw-window-handle", version = "0.3.4"},
    { name = "raw-window-handle", version = "0.4.3"},
    { name = "rustix", version = "0.37"},
    { name = "smithay-client-toolkit", version = "0.16"},
    { name = "smithay-client-toolkit", version = "0.18"},
    { name = "syn", version = "1"},
    { name = "wayland-client", version = "0.29"},
    { name = "wayland-cursor", version = "0.29"},
    { name = "wayland-protocols", version = "0.29"},
    { name = "wayland-scanner", version = "0.29"},
    { name = "wayland-sys", version = "0.29"},
    { name = "wayland-sys", version = "0.31"},
    { name = "windows-sys", version = "0.36"},
    { name = "windows-sys", version = "0.48"},
    { name = "windows-targets", version = "0.48"},
    { name = "windows_aarch64_msvc", version = "0.36"},
    { name = "windows_aarch64_msvc", version = "0.42"},
    { name = "windows_aarch64_msvc", version = "0.48"},
    { name = "windows_aarch64_gnullvm", version = "0.42"},
    { name = "windows_aarch64_gnullvm", version = "0.48"},
    { name = "windows_i686_gnu", version = "0.36"},
    { name = "windows_i686_gnu", version = "0.42"},
    { name = "windows_i686_gnu", version = "0.48"},
    { name = "windows_i686_msvc", version = "0.36"},
    { name = "windows_i686_msvc", version = "0.42"},
    { name = "windows_i686_msvc", version = "0.48"},
    { name = "windows_x86_64_gnu", version = "0.36"},
    { name = "windows_x86_64_gnu", version = "0.42"},
    { name = "windows_x86_64_gnu", version = "0.48"},
    { name = "windows_x86_64_gnullvm", version = "0.42"},
    { name = "windows_x86_64_gnullvm", version = "0.48"},
    { name = "windows_x86_64_msvc", version = "0.36"},
    { name = "windows_x86_64_msvc", version = "0.42"},
    { name = "windows_x86_64_msvc", version = "0.48"},
]

[sources]
unknown-git = "deny"
