name: Check and Test

on: workflow_call

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    uses: ./.github/workflows/fmt.yml

  check-and-test:
    name: "Check & Test"
    needs: fmt
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: sudo apt install libwayland-dev libasound2-dev

    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - name: Check
      run: cargo check --all-targets

    - name: Test
      run: cargo test --all-targets --verbose
